package com.example.serviceandnotification.Others

object Constants {

    const val FOREGROUND_SERVICE_LOG_TAG = "FR_SR_LOG_TAG"

    const val ACTION_START_OR_RESUME_FOREGROUND_SERVICE =
        "ACTION_START_OR_RESUME_FOREGROUND_SERVICE"

    const val ACTION_PAUSE_FOREGROUND_SERVICE =
        "ACTION_PAUSE_FOREGROUND_SERVICE"

    const val ACTION_STOP_FOREGROUND_SERVICE =
        "ACTION_STOP_FOREGROUND_SERVICE"

    const val FOREGROUND_SERVICE_CHANNEL_ID = "FOREGROUND SERVICE CHANNEL ID"
    const val FOREGROUND_SERVICE_CHANNEL_NAME = "FOREGROUND SERVICE CHANNEL NAME"
    const val SHOW_FOREGROUND_SERVICE1_FRAGMENT = "SHOW FOREGROUND SERVICE1 FRAGMENT"

    const val NOTIFICATION_ID = 1

}